/* Contenuti del sito, in italiano e inglese.
   main.js legge da qui per popolare le pagine e il menu. */
window.SITE_CONTENT = {
  it: {
    meta: {
      name: "Mariano Casaburi",
      role: "Ingegneria delle Telecomunicazioni / Software QA Specialist",
      siteTitle: "Mariano Casaburi — Curriculum",
    },
    nav: {
      home: "Home",
      about: "Chi sono",
      experience: "Esperienza",
      education: "Formazione",
      skills: "Competenze",
      languages: "Lingue",
      projects: "Progetti",
      contact: "Contatti",
    },
    footer: "Curriculum Vitae — aggiornato ad Agosto 2026",
    home: {
      eyebrow: "Curriculum Vitae",
      title: "Mariano Casaburi",
      role: "Ingegneria delle Telecomunicazioni / Software QA Specialist",
      ctaPrimary: "Scrivimi",
      ctaSecondary: "Scarica il CV",
      cvHref: "assets/Mariano_Casaburi_CV_IT.pdf",
      sectionLabel: "Esplora il profilo",
      cards: [
        { key: "about", n: "01", title: "Chi sono", desc: "15 anni nell'IT tra test, sviluppo e formazione." },
        { key: "experience", n: "02", title: "Esperienza professionale", desc: "Da E.M.M. Informatica ad Alten Italia." },
        { key: "education", n: "03", title: "Istruzione e formazione", desc: "Laurea in Ingegneria delle Telecomunicazioni e certificazioni." },
        { key: "skills", n: "04", title: "Competenze tecniche", desc: "Java, testing automatizzato, BDD, tool e DBMS." },
        { key: "languages", n: "05", title: "Lingue", desc: "Italiano madrelingua, Inglese B2." },
        { key: "projects", n: "06", title: "Progetti", desc: "Portfolio e progetti su telecomunicazioni satellitari." },
        { key: "contact", n: "07", title: "Contatti", desc: "Email, telefono e LinkedIn." },
      ],
    },
    about: {
      eyebrow: "Chi sono",
      title: "Su di me",
      subtitle: "Percorso professionale e attitudine al lavoro.",
      paragraphs: [
        "Lavoro nel settore IT da circa 15 anni. Ho ricoperto svariate posizioni: Tester, Scrum Master, Developer, Technical Writer.",
        "Contemporaneamente, ho conseguito la Laurea Specialistica in Ingegneria delle Telecomunicazioni pur essendo lavoratore Full Time.",
        "Amo la cultura STEM e tenermi aggiornato su ciò che riguarda scienza e tecnologie. Ho duttilità e propensione al risultato.",
        "Sul luogo di lavoro cerco sempre di avere una forte empatia con chi mi è intorno ed amo condividere le conoscenze che ho.",
      ],
      extra: { label: "Patente", value: "Tipo B" },
    },
    experience: {
      eyebrow: "Percorso",
      title: "Esperienza professionale",
      subtitle: "Ruoli ricoperti e principali responsabilità.",
      entries: [
        {
          period: "2024 — Attualmente",
          org: "ALTEN ITALIA",
          role: "QA Specialist per Aruba e Commissione Europea",
          desc: "Test Management, Analisi dei Requisiti, Definizione di Test Plan, Design e Scrittura Casi di Test, Automazione Java dei casi di test per il progetto SIMPL della Commissione Europea.",
          link: { label: "simpl-programme.ec.europa.eu", url: "https://simpl-programme.ec.europa.eu/" },
        },
        {
          period: "2015 — 2024",
          org: "E. M. M. INFORMATICA",
          role: "Software Automation Tester per Walgreens",
          desc: "Automazione dei casi di test con Java.",
        },
        {
          period: "2021 — 2023",
          org: "E. M. M. INFORMATICA",
          role: "Docente",
          desc: "Attività di docenza per la formazione degli stagisti sull'attività di test manuale e automatizzato.",
        },
      ],
      otherLabel: "Altre esperienze",
      other: "Software Developer per API con Java, WPF Developer con C#, Scrum Master, Technical Writer.",
    },
    education: {
      eyebrow: "Formazione",
      title: "Istruzione e formazione",
      subtitle: "Percorso accademico, certificazioni e corsi.",
      entries: [
        {
          period: "2009 — 2025",
          org: "Università di Benevento",
          role: "Laurea Specialistica in Ingegneria delle Telecomunicazioni",
          desc: "Titolo conseguito contemporaneamente all'attività lavorativa. Tesi di Laurea: “Trasferimento di Energia Solare da Satellite”.",
          link: { label: "Tesi di laurea (Google Drive)", url: "https://drive.google.com/file/d/1ZEWsjKGeQBmGH6EuE0YSj1KDs4HWbTB0/view?usp=drive_link" },
          exams: "ALGEBRA, CAMPI ELETTROMAGNETICI III, INGEGNERIA DEL SOFTWARE, LABORATORIO DI TRASMISSIONE NUMERICA, MATEMATICA III, METODI NUMERICI, MICROONDE II, MISURE SU RETI NUMERICHE DI TELECOMUNICAZIONE, SISTEMI DI COMUNICAZIONI SATELLITARI, SISTEMI DI TELERILEVAMENTO, ANTENNE II, BASI DI DATI, ELETTRONICA PER LE TELECOMUNICAZIONI, PROPAGAZIONE, RETI DI CALCOLATORI, TELERILEVAMENTO E DIAGNOSTICA ELETTROMAGNETICA, TEORIA DELL'INFORMAZIONE, TEORIA DELLA STIMA E RIVELAZIONE DEI SEGNALI, TRASMISSIONE NUMERICA II",
        },
        {
          period: "2000 — 2008",
          org: "Università di Benevento",
          role: "Laurea Triennale in Ingegneria delle Telecomunicazioni",
          desc: "Tesi di Laurea: “Analisi e Validazione di Algoritmi di Fire Detection da sensore MODIS della NASA”.",
          exams: "ANTENNE, ELABORAZIONE NUMERICA DEI SEGNALI, ELEMENTI D'INFORMATICA, MICROONDE, PROGRAMMAZIONE, PROGRAMMAZIONE DI SISTEMA, TEORIA DEI FENOMENI ALEATORI, TEORIA DEI SEGNALI, ECONOMIA ED ORGANIZZAZIONE AZIENDALE, ELETTRONICA PER LE TELECOMUNICAZIONI, FISICA 1, FISICA 2, FONDAMENTI DI INFORMATICA I, GEOMETRIA E ALGEBRA, INGLESE, MATEMATICA 1, MATEMATICA 2, NOZIONI GIURIDICHE FONDAMENTALI, CAMPI ELETTROMAGNETICI 1, CAMPI ELETTROMAGNETICI 2, ELETTRONICA, INTERAZIONE BIOELETTROMAGNETICA, METODI MATEMATICI, MICROONDE, MISURE ELETTRONICHE, PROGRAMMAZIONE DI SISTEMA, SISTEMI, TEORIA DEI CIRCUITI, ELABORAZIONE NUMERICA DEI SEGNALI, METODI NUMERICI IN ELETTROMAGNETISMO, OPTOELETTRONICA, PROGETTAZIONE AUTOMATICA IN ELETTROMAGNETISMO, RETI DI TELECOMUNICAZIONI, SISTEMI RADIOMOBILI, TIROCINIO, TRASMISSIONE NUMERICA",
        },
        {
          period: "2022",
          org: "ISTQB",
          role: "Certificazione ISTQB livello Foundation",
          desc: "Certificazione sui fondamenti del testing per la qualità del software.",
        },
      ],
      coursesLabel: "Corsi completati erogati da ALTEN",
      courses: [
        { title: "Python Base", desc: "Corso di fondamenti del linguaggio Python con prova finale." },
        { title: "AI Prompt Engineering Foundation", desc: "Corso di fondamenti di prompting per l'intelligenza artificiale." },
      ],
      examsToggle: "Esami sostenuti",
    },
    skills: {
      eyebrow: "Competenze",
      title: "Capacità e competenze tecniche",
      subtitle: "Linguaggi, strumenti e metodologie utilizzate quotidianamente.",
      groups: [
        { title: "Linguaggi", items: ["Java", "Matlab", "C#", "Python (base)"] },
        { title: "IDE", items: ["IntelliJ", "Eclipse", "Visual Studio Code (base)"] },
        { title: "Testing funzionale", items: ["Gherkin", "Approccio BDD", "Cucumber", "Selenium", "Playwright", "Postman"] },
        { title: "Tool", items: ["Jira"] },
        { title: "Office", items: ["Excel", "Word", "PowerPoint"] },
        { title: "DBMS", items: ["SQL Server", "MySQL", "CosmosDB"] },
        { title: "Framework Agile", items: ["Scrum"] },
      ],
      softTitle: "Soft skills",
      soft: ["Team working", "Problem solving", "Stress management", "Buone doti comunicative"],
    },
    languages: {
      eyebrow: "Lingue",
      title: "Competenze linguistiche",
      subtitle: "Lingue parlate e relativo livello.",
      items: [
        { name: "Italiano", level: "Madrelingua" },
        { name: "Inglese", level: "B2" },
      ],
    },
    projects: {
      eyebrow: "Progetti",
      title: "Progetti e portfolio",
      subtitle: "Lavori personali e progetti di approfondimento.",
      items: [
        {
          title: "Progetti TLC Satellitari",
          desc: "Repository dedicato a progetti sulle telecomunicazioni satellitari, inclusa l'analisi stocastica del budget di collegamento (ISL budget).",
          url: "https://github.com/ingachille82/isl-budget-stochastic",
        },
        {
          title: "Portfolio GitHub",
          desc: "Raccolta dei repository e dei progetti personali.",
          url: "https://github.com/ingachille82",
        },
      ],
    },
    contact: {
      eyebrow: "Contatti",
      title: "Mettiamoci in contatto",
      subtitle: "I canali migliori per raggiungermi.",
      items: [
        { k: "Telefono", v: "+39 392 857 9017", href: "tel:+393928579017" },
        { k: "Email", v: "mdcasaburi@gmail.com", href: "mailto:mdcasaburi@gmail.com" },
        { k: "LinkedIn", v: "linkedin.com/in/mariano-casaburi-2148ab45", href: "https://www.linkedin.com/in/mariano-casaburi-2148ab45" },
        { k: "GitHub", v: "github.com/ingachille82", href: "https://github.com/ingachille82" },
      ],
    },
  },

  en: {
    meta: {
      name: "Mariano Casaburi",
      role: "Telecommunications Engineering / Software QA Specialist",
      siteTitle: "Mariano Casaburi — Resume",
    },
    nav: {
      home: "Home",
      about: "About",
      experience: "Experience",
      education: "Education",
      skills: "Skills",
      languages: "Languages",
      projects: "Projects",
      contact: "Contact",
    },
    footer: "Curriculum Vitae — updated August 2026",
    home: {
      eyebrow: "Curriculum Vitae",
      title: "Mariano Casaburi",
      role: "Telecommunications Engineering / Software QA Specialist",
      ctaPrimary: "Get in touch",
      ctaSecondary: "Download CV",
      cvHref: "assets/Mariano_Casaburi_CV_EN.pdf",
      sectionLabel: "Explore the profile",
      cards: [
        { key: "about", n: "01", title: "About", desc: "15 years in IT across testing, development and training." },
        { key: "experience", n: "02", title: "Professional experience", desc: "From E.M.M. Informatica to Alten Italia." },
        { key: "education", n: "03", title: "Education & training", desc: "Degree in Telecommunications Engineering and certifications." },
        { key: "skills", n: "04", title: "Technical skills", desc: "Java, test automation, BDD, tools and DBMS." },
        { key: "languages", n: "05", title: "Languages", desc: "Native Italian, English B2." },
        { key: "projects", n: "06", title: "Projects", desc: "Portfolio and satellite telecommunications projects." },
        { key: "contact", n: "07", title: "Contact", desc: "Email, phone and LinkedIn." },
      ],
    },
    about: {
      eyebrow: "About",
      title: "About me",
      subtitle: "Professional path and approach to work.",
      paragraphs: [
        "I have worked in the IT sector for about 15 years, covering several roles: Tester, Scrum Master, Developer, Technical Writer.",
        "At the same time, I earned my Master's Degree in Telecommunications Engineering while working full time.",
        "I love STEM culture and staying up to date with science and technology. I'm adaptable and results-oriented.",
        "In the workplace, I always try to build strong empathy with the people around me and I enjoy sharing what I know.",
      ],
      extra: { label: "Driving licence", value: "Category B" },
    },
    experience: {
      eyebrow: "Career",
      title: "Professional experience",
      subtitle: "Roles held and key responsibilities.",
      entries: [
        {
          period: "2024 — Present",
          org: "ALTEN ITALIA",
          role: "QA Specialist for Aruba and the European Commission",
          desc: "Test management, requirements analysis, test plan definition, test case design and writing, Java automation of test cases for the European Commission's SIMPL project.",
          link: { label: "simpl-programme.ec.europa.eu", url: "https://simpl-programme.ec.europa.eu/" },
        },
        {
          period: "2015 — 2024",
          org: "E. M. M. INFORMATICA",
          role: "Software Automation Tester for Walgreens",
          desc: "Test case automation with Java.",
        },
        {
          period: "2021 — 2023",
          org: "E. M. M. INFORMATICA",
          role: "Trainer",
          desc: "Training activity for interns on manual and automated testing.",
        },
      ],
      otherLabel: "Other experience",
      other: "Software Developer for APIs with Java, WPF Developer with C#, Scrum Master, Technical Writer.",
    },
    education: {
      eyebrow: "Education",
      title: "Education & training",
      subtitle: "Academic path, certifications and courses.",
      entries: [
        {
          period: "2009 — 2025",
          org: "University of Benevento",
          role: "Master's Degree in Telecommunications Engineering",
          desc: "Degree earned while working full time. Thesis: “Solar Power Transfer from Satellite”.",
          link: { label: "Thesis (Google Drive)", url: "https://drive.google.com/file/d/1ZEWsjKGeQBmGH6EuE0YSj1KDs4HWbTB0/view?usp=drive_link" },
          exams: "ALGEBRA, ELECTROMAGNETIC FIELDS III, SOFTWARE ENGINEERING, DIGITAL TRANSMISSION LAB, MATHEMATICS III, NUMERICAL METHODS, MICROWAVES II, MEASUREMENTS ON DIGITAL TELECOMMUNICATION NETWORKS, SATELLITE COMMUNICATION SYSTEMS, REMOTE SENSING SYSTEMS, ANTENNAS II, DATABASES, ELECTRONICS FOR TELECOMMUNICATIONS, PROPAGATION, COMPUTER NETWORKS, REMOTE SENSING AND ELECTROMAGNETIC DIAGNOSTICS, INFORMATION THEORY, ESTIMATION AND SIGNAL DETECTION THEORY, DIGITAL TRANSMISSION II (course names kept in Italian, as officially recorded)",
        },
        {
          period: "2000 — 2008",
          org: "University of Benevento",
          role: "Bachelor's Degree in Telecommunications Engineering",
          desc: "Thesis: “Analysis and Validation of Fire Detection Algorithms from NASA's MODIS Sensor”.",
          exams: "ANTENNAS, DIGITAL SIGNAL PROCESSING, COMPUTER SCIENCE BASICS, MICROWAVES, PROGRAMMING, SYSTEM PROGRAMMING, RANDOM PHENOMENA THEORY, SIGNAL THEORY, BUSINESS ECONOMICS AND ORGANIZATION, ELECTRONICS FOR TELECOMMUNICATIONS, PHYSICS 1, PHYSICS 2, COMPUTER SCIENCE FUNDAMENTALS I, GEOMETRY AND ALGEBRA, ENGLISH, MATHEMATICS 1, MATHEMATICS 2, LEGAL FUNDAMENTALS, ELECTROMAGNETIC FIELDS 1, ELECTROMAGNETIC FIELDS 2, ELECTRONICS, BIOELECTROMAGNETIC INTERACTION, MATHEMATICAL METHODS, MICROWAVES, ELECTRONIC MEASUREMENTS, SYSTEM PROGRAMMING, SYSTEMS, CIRCUIT THEORY, DIGITAL SIGNAL PROCESSING, NUMERICAL METHODS IN ELECTROMAGNETISM, OPTOELECTRONICS, AUTOMATED DESIGN IN ELECTROMAGNETISM, TELECOMMUNICATION NETWORKS, MOBILE RADIO SYSTEMS, INTERNSHIP, DIGITAL TRANSMISSION (course names kept in Italian, as officially recorded)",
        },
        {
          period: "2022",
          org: "ISTQB",
          role: "ISTQB Foundation Level Certification",
          desc: "Certification on the fundamentals of software quality testing.",
        },
      ],
      coursesLabel: "Courses completed through ALTEN",
      courses: [
        { title: "Python Basics", desc: "Fundamentals course on the Python language with a final assessment." },
        { title: "AI Prompt Engineering Foundation", desc: "Fundamentals course on prompting for AI." },
      ],
      examsToggle: "Exams taken",
    },
    skills: {
      eyebrow: "Skills",
      title: "Technical skills",
      subtitle: "Languages, tools and methodologies used day to day.",
      groups: [
        { title: "Languages", items: ["Java", "Matlab", "C#", "Python (basic)"] },
        { title: "IDE", items: ["IntelliJ", "Eclipse", "Visual Studio Code (basic)"] },
        { title: "Functional testing", items: ["Gherkin", "BDD approach", "Cucumber", "Selenium", "Playwright", "Postman"] },
        { title: "Tools", items: ["Jira"] },
        { title: "Office", items: ["Excel", "Word", "PowerPoint"] },
        { title: "DBMS", items: ["SQL Server", "MySQL", "CosmosDB"] },
        { title: "Agile framework", items: ["Scrum"] },
      ],
      softTitle: "Soft skills",
      soft: ["Team working", "Problem solving", "Stress management", "Strong communication skills"],
    },
    languages: {
      eyebrow: "Languages",
      title: "Language skills",
      subtitle: "Spoken languages and proficiency level.",
      items: [
        { name: "Italian", level: "Native" },
        { name: "English", level: "B2" },
      ],
    },
    projects: {
      eyebrow: "Projects",
      title: "Projects & portfolio",
      subtitle: "Personal work and side projects.",
      items: [
        {
          title: "Satellite TLC Projects",
          desc: "Repository dedicated to satellite telecommunications projects, including stochastic analysis of the inter-satellite link (ISL) budget.",
          url: "https://github.com/ingachille82/isl-budget-stochastic",
        },
        {
          title: "GitHub Portfolio",
          desc: "Collection of personal repositories and projects.",
          url: "https://github.com/ingachille82",
        },
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Let's get in touch",
      subtitle: "The best channels to reach me.",
      items: [
        { k: "Phone", v: "+39 392 857 9017", href: "tel:+393928579017" },
        { k: "Email", v: "mdcasaburi@gmail.com", href: "mailto:mdcasaburi@gmail.com" },
        { k: "LinkedIn", v: "linkedin.com/in/mariano-casaburi-2148ab45", href: "https://www.linkedin.com/in/mariano-casaburi-2148ab45" },
        { k: "GitHub", v: "github.com/ingachille82", href: "https://github.com/ingachille82" },
      ],
    },
  },
};
